export const site = 'https://moocsoft.net';
export const published = '2026-09-12';

export const apps = {
  nutrition: {
    name: 'NutriLens', slug: 'nutrilens', category: 'Nutrition', color: '#ff9878',
    icon: '/assets/apps/nutrilens/icon.jpg',
    promise: 'Scan a meal. Explore estimated calories and macros.',
    platform: 'iPhone, iPad & Android · Optional in-app purchases',
    apple: 'https://apps.apple.com/us/app/nutrilens-food-ai-scanner/id6755138291',
    google: 'https://play.google.com/store/apps/details?id=com.moocsoft.food_scan_ai',
    tool: 'calorie-macro-calculator', toolName: 'Calorie & Macro Calculator',
    heading: 'Food tracking and nutrition guides',
    description: 'Learn to read calories and macros, estimate homemade meals, and keep a useful food photo log with practical examples and NutriLens.',
    intro: 'A meal photo is a starting point for understanding food. These guides show you how to check a portion, read the numbers and keep a record that is useful the next time you eat a similar meal.',
    choice: 'Start with the photo guide if you want a quick estimate. Choose the homemade-meals worksheet when you know the ingredients. The calories-versus-macros guide explains the numbers, and the photo-log guide turns occasional scans into a repeatable routine.',
    use: 'NutriLens analyzes meal photos and provides estimated calories and macronutrients. Check the identified food and portion before using a result. Hidden ingredients and cooking methods can change the estimate.',
    toolHeading: 'Calorie and Macro Calculator',
    landingHeading: 'An AI food scanner for everyday meals.',
  },
  savings: {
    name: 'Savings Goal Tracker', slug: 'savings-goal-tracker', category: 'Saving money', color: '#76dfb4',
    icon: '/assets/apps/savings-goal-tracker/icon.jpg',
    promise: 'Give every savings goal a target and track your contributions.',
    platform: 'iPhone, iPad & Android · Optional in-app purchases',
    apple: 'https://apps.apple.com/us/app/savings-goal-tracker/id6450431254',
    google: 'https://play.google.com/store/apps/details?id=com.moocsoft.goal_tracker',
    tool: '52-week-savings-calculator', toolName: '52-Week Savings Calculator',
    heading: 'Savings challenges and goal-planning guides',
    description: 'Plan a 52-week savings challenge, compare reverse deposits, separate savings goals, and calculate contributions with worked examples.',
    intro: 'A savings plan needs three things: a purpose, an amount and a contribution you can actually make. Work through the examples here, then keep a record of real deposits in Savings Goal Tracker.',
    choice: 'Use the standard challenge for gradually increasing deposits, or compare the reverse version if your available money changes during the year. For a fixed deadline, start with the savings-goal formula. Use the separate-funds guide when several goals compete for the same money.',
    use: 'Savings Goal Tracker lets you organize targets and record progress toward them. A recorded contribution is a record, not a bank transfer. Keep the app totals aligned with money you have actually set aside.',
    toolHeading: '52-Week Savings Challenge Calculator',
    landingHeading: 'A savings goal tracker for every next step.',
  },
  quitting: {
    name: 'QuitBit', slug: 'quitbit', category: 'Quitting smoking', color: '#84c5ff',
    icon: '/assets/apps/quitbit/icon.jpg',
    promise: 'Track your smoke-free time, savings and personal milestones.',
    platform: 'iPhone & iPad · Optional in-app purchases',
    apple: 'https://apps.apple.com/us/app/quitbit-break-bad-habits/id6747658536',
    tool: 'quit-smoking-savings-calculator', toolName: 'Quit Smoking Savings Calculator',
    heading: 'Smoke-free progress and savings guides',
    description: 'Calculate cigarette costs, plan personal quit milestones, keep a trigger journal, and record progress with QuitBit and free worksheets.',
    intro: 'A counter can make progress visible. A journal can help you remember what a difficult moment was like. These guides focus on recording your experience and planning practical next steps alongside appropriate quit-smoking support.',
    choice: 'Start with cigarette costs for a personal savings estimate. The milestone guide helps you choose checkpoints. Use the trigger journal to notice recurring situations, and the setback guide when you need to update your record and begin again.',
    use: 'QuitBit provides abstinence counters, savings tracking, milestones and a mood journal. These are ways to record your journey; they do not diagnose or treat nicotine dependence. A healthcare professional or quitline can help you choose cessation support.',
    toolHeading: 'Quit Smoking Savings Calculator',
    landingHeading: 'Track your smoke-free progress with QuitBit.',
  },
  training: {
    name: 'Did You Lift', slug: 'did-you-lift', category: 'Workout planning', color: '#d8ff3e',
    icon: '/assets/apps/did-you-lift/icon.png',
    promise: 'Plan your gym week, follow set targets and time your rests.',
    platform: 'Android · Optional lifetime Premium',
    google: 'https://play.google.com/store/apps/details?id=com.moocsoft.didyoulift',
    tool: 'workout-volume-rest-timer', toolName: 'Workout Volume Calculator & Rest Timer',
    heading: 'Workout logging and gym-planning guides',
    description: 'Learn how to log gym workouts, calculate training volume, use a rest timer, and organize a weekly routine with Did You Lift.',
    intro: 'A useful workout record tells you what you planned and what you completed. Learn how to keep those numbers clear, compare like-for-like sessions and organize a weekly routine before you walk into the gym.',
    choice: 'Begin with the workout-log template if you are starting a record. Read the volume guide before comparing totals. The timer guide covers the gap between sets, while the weekly-planning guide helps you put an existing program into a workable calendar.',
    use: 'Did You Lift lets you plan exercises with individual set targets and move from a completed set into a rest countdown. Use a training plan suited to your experience and adjust targets with your coach when needed.',
    toolHeading: 'Workout Volume Calculator and Rest Timer',
    landingHeading: 'Your workout log and gym planner.',
  },
  habits: {
    name: 'Habit Tracker Daily', slug: 'habit-tracker', category: 'Daily habits', color: '#d4acff',
    icon: '/assets/apps/habit-tracker/icon.jpg',
    promise: 'Build flexible routines and see your progress on a calendar.',
    platform: 'iPhone & iPad · Optional in-app purchases',
    apple: 'https://apps.apple.com/us/app/habit-tracker-daily/id6572323963',
    tool: 'habit-streak-calendar', toolName: 'Habit Streak Calendar',
    heading: 'Habit tracking and routine-building guides',
    description: 'Start a habit tracker, choose daily or weekly schedules, calculate completion rates, and restart a routine with practical calendar examples.',
    intro: 'A good habit record is easy to understand on a busy day. Choose a clear action, give it a realistic schedule and use the calendar to learn from what happened instead of guessing from memory.',
    choice: 'Start with one habit and a definition of done. Then choose a daily or weekly schedule. Use the streak-versus-completion guide to interpret your record, and the restart worksheet when the original routine stops fitting your life.',
    use: 'Habit Tracker Daily supports flexible repeat schedules, calendar check-ins and progress charts. Your habit data stays on your device, with file export available when you want a copy or need to move it.',
    toolHeading: 'Habit Streak Calendar',
    landingHeading: 'A daily habit tracker that fits your life.',
  },
};

export const sources = {
  portions: ['FDA: Serving size on the Nutrition Facts label', 'https://www.fda.gov/food/nutrition-facts-label/serving-size-nutrition-facts-label'],
  energy: ['USDA FoodData Central: Nutrient and energy calculations', 'https://fdc.nal.usda.gov/Foundation_Foods_Documentation/'],
  savings: ['CFPB: Your Money, Your Goals savings worksheets', 'https://www.consumerfinance.gov/consumer-tools/educator-tools/your-money-your-goals/toolkit/'],
  emergency: ['CFPB: Building an emergency fund', 'https://www.consumerfinance.gov/an-essential-guide-to-building-an-emergency-fund/'],
  quitplan: ['Smokefree.gov: Build a quit plan', 'https://smokefree.gov/build-your-quit-plan'],
  triggers: ['Smokefree.gov: Cravings and triggers', 'https://smokefree.gov/challenges-when-quitting/cravings-triggers'],
  slip: ['Smokefree.gov: Get back on track after a setback', 'https://smokefree.gov/challenges-when-quitting/stick-with-it/get-back-on-track'],
  withdrawal: ['Smokefree.gov: Managing nicotine withdrawal', 'https://smokefree.gov/challenges-when-quitting/withdrawal/managing-nicotine-withdrawal'],
  activity: ['CDC: Adult physical activity overview', 'https://www.cdc.gov/physical-activity-basics/guidelines/adults.html'],
};

export const escape = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
export const table = (caption, headers, rows) => `<div class="guide-table" tabindex="0" role="region" aria-label="${escape(caption)}"><table><caption>${escape(caption)}</caption><thead><tr>${headers.map(h => `<th scope="col">${escape(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row => `<tr>${row.map((value, i) => i ? `<td>${escape(value)}</td>` : `<th scope="row">${escape(value)}</th>`).join('')}</tr>`).join('')}</tbody></table></div>`;
