import nutrition from './nutrition.mjs';
import moreNutrition from './nutrition-more.mjs';
import restaurantNutrition from './nutrition-restaurants.mjs';
import nutritionAccuracy from './nutrition-accuracy.mjs';
import savings from './savings.mjs';
import moreSavings from './savings-more.mjs';
import savingsChallenges from './savings-challenges.mjs';
import irregularSavings from './savings-irregular.mjs';
import quitting from './quitting.mjs';
import moreQuitting from './quitting-more.mjs';
import training from './training.mjs';
import moreTraining from './training-more.mjs';
import trainingSetTypes from './training-set-types.mjs';
import habits from './habits.mjs';
import moreHabits from './habits-more.mjs';
import math from './math.mjs';
import moreMath from './math-more.mjs';
import mathPractice from './math-practice.mjs';
import mathPatterns from './math-patterns.mjs';
import mathRoundRobin from './math-round-robin.mjs';
import weeklyReset from './weekly-reset.mjs';
import mobileDevelopment from './mobile-development.mjs';

export const guides = [...nutrition, ...moreNutrition, ...restaurantNutrition, ...nutritionAccuracy, ...savings, ...moreSavings, ...savingsChallenges, ...irregularSavings, ...moreQuitting, ...quitting, ...training, ...moreTraining, ...trainingSetTypes, ...habits, ...moreHabits, ...weeklyReset, ...math, ...moreMath, ...mathPractice, ...mathPatterns, ...mathRoundRobin, ...mobileDevelopment];
