import { table } from './apps.mjs';

export default [
  {
    topic: 'math', slug: 'missing-number-puzzles-with-answers', published: '2026-10-01', appPreview: true,
    title: 'Missing Number Puzzles With Answers: 5 Worked Examples',
    description: 'Solve five missing-number puzzles with hidden answers, row-rule examples and a checking method. Continue with Moocsoft’s math puzzle app when you want more.',
    intro: 'Missing-number puzzles ask you to explain a relationship, not just fill a blank. Try these five original examples before opening each answer, then check whether your rule works everywhere it should.',
    takeaway: 'Find what repeats across the complete rows, state the rule in words, and substitute every number back into it. A rule that fits only one row is not enough.',
    sections: [
      ['How to use these practice puzzles', `<p>Use a note or work mentally. There is no time limit on this page, and each answer stays hidden until you open it. The examples below were written for this guide; they are not a list of solutions to numbered levels in the app.</p><p>If you enjoy this kind of reasoning, <a href="/math-riddles/">Moocsoft’s Math Riddles / Math Puzzles app</a> offers a separate puzzle journey with hints and solutions. First try the free examples here to see whether the style suits you.</p><p>For a row puzzle, keep the direction consistent: use the first two entries to explain the third. For a conventional equation, use normal arithmetic rather than inventing a new meaning for the equals sign.</p>`],
      ['Puzzle 1: complete a balanced equation', `<p class="guide-formula">□ + 18 = 47</p><p>What number belongs in the box? Think about the operation that reverses adding 18.</p><div class="guide-faq"><details><summary>Reveal answer and check</summary><p><strong>29.</strong> Subtract 18 from both sides: 47 − 18 = 29. Substitute the result: 29 + 18 = 47. The check matters because it tests the original equation, not just your subtraction.</p></details></div><p>A missing value may appear on either side of an equation. Rewrite the statement carefully before calculating; 18 − □ = 47 would be a different problem.</p>`],
      ['Puzzle 2: find the repeated row total', table('Every row follows the same addition rule', ['First number', 'Second number', 'Result'], [['6','9','15'],['8','5','13'],['7','12','?']]) + `<p>Use addition to explain the complete rows, then finish the last row.</p><div class="guide-faq"><details><summary>Reveal answer and check</summary><p><strong>19.</strong> The first two numbers add to the result: 6 + 9 = 15 and 8 + 5 = 13. Therefore 7 + 12 = 19. The rule is the same in all three rows.</p></details></div>`],
      ['Puzzle 3: multiply, then make one adjustment', table('Use multiplication followed by the same subtraction', ['First number', 'Second number', 'Result'], [['3','4','10'],['5','3','13'],['6','4','?']]) + `<p>Start by multiplying the first two numbers. How far is each product from the displayed result?</p><div class="guide-faq"><details><summary>Reveal answer and check</summary><p><strong>22.</strong> Each result is the product minus 2: (3 × 4) − 2 = 10 and (5 × 3) − 2 = 13. Apply it again: (6 × 4) − 2 = 22. Do not subtract 2 from one input before multiplying; that changes the grouping.</p></details></div>`],
      ['Puzzle 4: recover the missing input', table('The rule is first number × second number + first number', ['First number', 'Second number', 'Result'], [['2','5','12'],['3','4','15'],['4','?','28']]) + `<p>This time the blank is an input, not the output. Work backward from 28 using the stated rule.</p><div class="guide-faq"><details><summary>Reveal answer and check</summary><p><strong>6.</strong> The final row means 4 × □ + 4 = 28. Subtract 4 to get 4 × □ = 24, then divide by 4. Check the complete statement: 4 × 6 + 4 = 28.</p></details></div>`],
      ['Puzzle 5: compare two squared values', table('Square each input, then subtract the second square from the first', ['First number', 'Second number', 'Result'], [['5','3','16'],['7','4','33'],['9','5','?']]) + `<p>Keep the two squares separate. Squaring a difference is not the same operation as subtracting two squares.</p><div class="guide-faq"><details><summary>Reveal answer and check</summary><p><strong>56.</strong> The rows give 5² − 3² = 25 − 9 = 16 and 7² − 4² = 49 − 16 = 33. The missing result is 9² − 5² = 81 − 25 = 56. In contrast, (9 − 5)² would be 16.</p></details></div>`],
      ['Choose the next kind of puzzle', `<p>If the arithmetic was easy but choosing a rule was difficult, try the <a href="/guides/math-puzzle-strategies/">hidden-rule strategy guide</a>. If the layout is a list rather than a grid, use the <a href="/guides/how-to-solve-number-pattern-puzzles/">number-pattern walkthrough</a>. If brackets caused mistakes, work through the <a href="/guides/order-of-operations-puzzles/">order-of-operations puzzles</a>.</p><p>For new questions on your phone, download the app using the store buttons above. Make an attempt before using a hint, then compare the explanation with your own reasoning. These row examples specify their rule family because a small set of numbers can otherwise support more than one constructed rule.</p>`],
    ], sources: [],
    faq: [['Are these answers for specific Math Riddles app levels?', 'No. These are original practice examples for the website, not a walkthrough of numbered app levels.'], ['Can a missing-number grid have more than one answer?', 'Without constraints, a small grid may fit multiple rules. These exercises give a rule or rule family to make the intended task clear.'], ['How should I check a missing input?', 'Put your answer back into the original equation or row rule and calculate the result again.']],
  },
  {
    topic: 'math', slug: 'order-of-operations-puzzles', published: '2026-10-01', appPreview: true,
    title: 'Order of Operations Puzzles: 6 Questions With Answers',
    description: 'Try six order-of-operations puzzles with explained answers. Practise brackets, multiplication and left-to-right evaluation before your next math game.',
    intro: 'Many quick arithmetic mistakes come from doing a correct operation at the wrong time. These six practice questions make the grouping explicit, so you can check your method without arguing over ambiguous notation.',
    takeaway: 'Evaluate brackets and powers first. Multiplication and division share a priority and run left to right; addition and subtraction also share a priority and run left to right.',
    sections: [
      ['Use the priority rules, not the letters alone', `<p>PEMDAS and BODMAS are reminders for the same basic convention. Neither means that multiplication always comes before division, or that addition always comes before subtraction. Operations in each equal-priority pair are evaluated from left to right.</p><p>Write one intermediate line rather than trying to hold the whole expression in memory. For 18 − 3 × 4, first calculate 3 × 4 = 12, then 18 − 12 = 6. Subtracting 3 from 18 first would answer a different, bracketed question.</p><p>The exercises are original website practice, not copied app levels. You can continue with <a href="/math-riddles/">Moocsoft’s math puzzle app</a> when you want a separate set of arithmetic and logic challenges.</p>`],
      ['Questions 1 and 2: the brackets change the answer', `<p class="guide-formula">1. 8 + 4 × 3<br>2. (8 + 4) × 3</p><p>Calculate both before opening the answer. The same three numbers appear, but they are not grouped in the same way.</p><div class="guide-faq"><details><summary>Reveal both answers</summary><p><strong>1: 20.</strong> Multiply 4 × 3 = 12, then add 8. <strong>2: 36.</strong> Complete the bracket first: 8 + 4 = 12, then multiply by 3. The brackets tell you which total is being multiplied.</p></details></div><p>When checking a puzzle image, read the symbols as carefully as the numbers. A bracket is part of the question, not decoration.</p>`],
      ['Questions 3 and 4: equal priority means left to right', `<p class="guide-formula">3. 24 ÷ 6 × 2<br>4. 17 − 8 + 3</p><p>There are no brackets to change the order. In question 3, division and multiplication share priority. In question 4, subtraction and addition share priority.</p><div class="guide-faq"><details><summary>Reveal both answers</summary><p><strong>3: 8.</strong> Work left to right: 24 ÷ 6 = 4, then 4 × 2 = 8. Do not turn the expression into 24 ÷ (6 × 2). <strong>4: 12.</strong> Calculate 17 − 8 = 9, then 9 + 3 = 12. Adding 8 and 3 first would insert brackets that were not there.</p></details></div>`],
      ['Questions 5 and 6: combine a power with a bracket', `<p class="guide-formula">5. 3² + 2 × 5<br>6. 30 ÷ (2 + 3) + 4²</p><p>Resolve each bracket or power, then finish the remaining expression using the same rules.</p><div class="guide-faq"><details><summary>Reveal both answers</summary><p><strong>5: 19.</strong> The square is 9 and the product is 10; 9 + 10 = 19. <strong>6: 22.</strong> The bracket is 5 and 4² is 16. You now have 30 ÷ 5 + 16 = 6 + 16 = 22.</p></details></div><p>Notice that 3² means 3 × 3, not 3 × 2. If powers are unfamiliar, expand them into repeated multiplication on a separate line before continuing.</p>`],
      ['Keep a useful mistake log', table('Turn an incorrect answer into a specific check', ['Mistake', 'What to check next time'], [['Added before multiplying','Mark multiplication or division before the final addition'],['Multiplied before a division to its left','Treat multiplication and division as one priority level'],['Ignored a bracket','Rewrite the bracket as one intermediate value'],['Read a square as doubling','Expand the power as repeated multiplication']]) + `<p>Record the line where your method changed the expression, rather than writing only “wrong.” Then change one number and solve a fresh example. For instance, after correcting 24 ÷ 6 × 2, try 36 ÷ 9 × 3; the answer is 12.</p><p>Do not train speed using expressions whose grouping is unclear. Write explicit multiplication symbols and brackets instead of relying on cramped or ambiguous image layouts.</p>`],
      ['Take the method into a math game', `<p>Try a short round in the app after you can explain the six examples. The Google Play version includes arithmetic mini-games alongside the main riddle journey; some additional modes require Premium. Use the current store listing to check what is included on your platform.</p><p>A timer does not change the arithmetic rules. If you make repeated errors, return to a written intermediate step before trying to answer faster. For the next exercise, try <a href="/guides/missing-number-puzzles-with-answers/">missing-number puzzles</a> or practise <a href="/guides/mental-multiplication-tricks/">mental multiplication shortcuts</a>.</p>`],
    ], sources: [],
    faq: [['Does multiplication always come before division?', 'No. They have equal priority. Evaluate them from left to right unless brackets specify a different grouping.'], ['Do BODMAS and PEMDAS give different answers?', 'Not when applied correctly to the same clearly written expression. Both put multiplication/division at one priority level and addition/subtraction at another.'], ['Can I solve these questions without installing the app?', 'Yes. Every question and explanation on this page is available in your browser. The app offers a separate collection for continued play.']],
  },
  {
    topic: 'math', slug: 'mental-multiplication-tricks', published: '2026-10-01', appPreview: true,
    title: 'Mental Multiplication Tricks: 5 Shortcuts With Practice',
    description: 'Learn five mental multiplication shortcuts for ×9, ×11, ×25 and near-round numbers, then test them with hidden answers and a short math-game routine.',
    intro: 'A useful multiplication shortcut makes the calculation easier to explain, not just faster to guess. These five methods replace an awkward product with smaller steps that keep exactly the same value.',
    takeaway: 'Split one factor into friendly parts, compensate around a round number, or double one factor while halving the other. Estimate first and check that the final product is plausible.',
    sections: [
      ['Split an awkward factor into tens and units', `<p>For <strong>23 × 7</strong>, split 23 into 20 + 3. Calculate 20 × 7 = 140 and 3 × 7 = 21, then add them: 161. This works because multiplication distributes across addition.</p><p>The same method handles 14 × 12: (14 × 10) + (14 × 2) = 140 + 28 = 168. Keep both products visible mentally or on paper so you do not accidentally add the unused factor rather than its product.</p><p>These are practice examples for this guide. <a href="/math-riddles/">Moocsoft’s Math Riddles / Math Puzzles app</a> provides separate number challenges when you want to use the method in a game.</p>`],
      ['Multiply by 9 or 11 using a nearby ten', `<p>To multiply a number by 9, multiply by 10 and subtract the original number. For 46 × 9: 460 − 46 = <strong>414</strong>. You are removing one group of 46 from ten groups.</p><p>For ×11, add that group instead: 46 × 11 = 460 + 46 = <strong>506</strong>. This approach handles carries naturally and does not depend on a digit trick that may fail when the digits sum above nine.</p><p>For ×99, use 100 groups minus one: 37 × 99 = 3,700 − 37 = 3,663. Choose this only when the subtraction is easier for you than splitting the product another way.</p>`],
      ['Multiply by 25 as one quarter of 100', `<p>Because 25 = 100 ÷ 4, multiplying by 25 is equivalent to multiplying by 100 and dividing by 4. With <strong>28 × 25</strong>, it is easier to divide 28 first: 28 ÷ 4 = 7, then 7 × 100 = <strong>700</strong>.</p><p>If the number is not divisible by four, keep the remainder or use another method. For 18 × 25, 18 × 100 ÷ 4 = 1,800 ÷ 4 = 450. Do not round 18 ÷ 4 down to 4; that would discard part of the product.</p>`],
      ['Double one factor and halve the other', `<p>For <strong>16 × 35</strong>, halve 16 and double 35 to get 8 × 70 = <strong>560</strong>. The product is unchanged because the factor of two cancels: (16 ÷ 2) × (35 × 2) = 16 × 35.</p><p>You can repeat the move while it helps. With 32 × 125, use 16 × 250, then 8 × 500 = 4,000. Stop when the next step is less convenient; a shortcut is useful only if you can follow it reliably.</p><p>Do not halve both factors. That makes the product one quarter of the original rather than keeping it unchanged.</p>`],
      ['Use a nearby round number and compensate', `<p>For <strong>19 × 6</strong>, calculate 20 × 6 = 120 and subtract one group of 6: <strong>114</strong>. For 51 × 8, calculate 50 × 8 = 400 and add one group of 8: 408.</p><p>Pay attention to the size of the adjustment. In 98 × 7, you moved up by two groups to reach 100 × 7. Subtract 2 × 7 = 14, not just 2: 700 − 14 = 686.</p>`],
      ['Try a six-question practice round', table('Choose a method before calculating', ['Question', 'Suggested starting point'], [['34 × 6','Split 34 into 30 + 4'],['27 × 9','Ten groups minus one'],['58 × 11','Ten groups plus one'],['36 × 25','Divide by four, multiply by 100'],['24 × 15','Halve and double'],['49 × 8','Use 50 groups, subtract one']]) + `<div class="guide-faq"><details><summary>Reveal the six worked answers</summary><p><strong>34 × 6 = 204:</strong> 180 + 24. <strong>27 × 9 = 243:</strong> 270 − 27. <strong>58 × 11 = 638:</strong> 580 + 58. <strong>36 × 25 = 900:</strong> 9 × 100. <strong>24 × 15 = 360:</strong> 12 × 30. <strong>49 × 8 = 392:</strong> 400 − 8.</p></details></div><p>If your answer differs, check the intermediate step before starting again. For 49 × 8, an estimate of about 400 is a useful warning if your final answer has an extra zero.</p>`],
      ['Choose a small challenge for your next session', `<p>Pick one method and solve three new examples before mixing methods. Once the steps feel clear, try the app’s number challenges and see which shortcut you actually recognize while playing. This is arithmetic practice, not a promise of an IQ increase or a measured cognitive benefit.</p><p>For a broader routine, use <a href="/guides/mental-math-games-for-adults/">mental math games for adults</a>. To avoid losing an otherwise correct calculation to grouping, review <a href="/guides/order-of-operations-puzzles/">order of operations</a>. If you prefer competition, read the <a href="/guides/play-math-games-with-friends/">friendly 1v1 setup guide</a> and check the app’s current room options.</p>`],
    ], sources: [],
    faq: [['Which multiplication shortcut should I learn first?', 'Start by splitting a factor into tens and units. It applies widely and makes the reasoning visible. Add the other methods when they simplify a particular product.'], ['Does doubling and halving always preserve the product?', 'Yes, when you double one factor and halve the other exactly. Rounding during the step changes the result.'], ['Should I start with timed multiplication practice?', 'You can start without a timer and add time pressure only when you can explain and check the method. Speed is not a substitute for correct steps.']],
  },
];
