import { table } from './apps.mjs';

export default [
  {
    topic: 'nutrition', slug: 'how-to-take-food-photos-for-calorie-tracking', published: '2026-09-22', modified: '2026-09-22',
    title: 'How to Take Food Photos for Better Calorie Estimates',
    description: 'Use a simple food-photo checklist to show portions, ingredients and scale more clearly before reviewing an AI calorie and macro estimate.',
    intro: 'A calorie scanner can only work with what the camera shows. Better lighting and a clear view will not make a photo exact, but they can reduce avoidable ambiguity before you review the result.',
    takeaway: 'Photograph the full plate in even light, include a useful size reference and keep a separate note of ingredients the camera cannot see.',
    sections: [
      ['Show the whole meal from a useful angle', `<p>Place the plate on a steady surface and keep every food item inside the frame. A view from roughly 45 degrees often shows both the surface of the food and its height. A top-down photo can be useful for a flat plate, while a side view may better reveal a deep bowl or stacked ingredients.</p><p>Avoid cropping the rim of the plate. The relationship between the food and its container provides context, even though plate size still varies.</p>`],
      ['Use even light and avoid strong filters', `<p>Natural window light or a bright room usually makes ingredients easier to distinguish. Strong shadows can merge foods together, while a warm color filter can change how sauces and cooked ingredients appear.</p><p>Wipe the camera lens, hold the phone still and check that the image is in focus. You do not need studio lighting; the goal is a readable record of the meal.</p>`],
      ['Give the photo some scale', table('Helpful and less-helpful scale clues', ['Scale clue', 'How it helps', 'Limitation'], [
        ['Visible plate or bowl', 'Shows how much of the container is filled', 'Container sizes differ'],
        ['Known package or label', 'Can show a declared serving size', 'The served amount may differ'],
        ['Second angle', 'Shows depth or stacked food', 'Still not a measurement'],
        ['Measured ingredient note', 'Adds information the photo cannot infer', 'Keep it in your own notes or food diary'],
      ]) + `<p>If accuracy matters for a particular meal, a measured ingredient or package label is stronger evidence than a visual comparison. Use the photo for convenience and record known quantities in your separate food diary.</p>`],
      ['Record what the camera cannot see', `<p>Cooking oil, dressing, butter, sugar and ingredients inside a mixed dish may be partly or completely hidden. Write them in your own notes while the meal is fresh in your memory. For a homemade recipe, keep the batch ingredients and number of portions together.</p><p>Do not use a food photo to determine whether a meal is safe for an allergy. An image cannot reliably reveal cross-contact or every ingredient.</p>`],
      ['Review the NutriLens result before saving it', `<p>After scanning, compare the food names and portion assumptions with the meal you know. If something is missing or misidentified, keep that discrepancy in a separate note rather than treating the estimate as a measured result.</p><p>Repeating the same photo setup for familiar meals makes the images easier to compare. NutriLens supports saving and revisiting scans; the iOS App Store listing includes this in Premium. Check the access available in your version before relying on app history. Your separate ingredient notes provide context alongside that history.</p>`],
    ],
    sources: ['portions'],
    faq: [['What angle is best for a food photo?', 'Use the angle that shows both the full meal and its depth. A 45-degree view works for many plates; top-down can work for flat meals, and a second side view can clarify a bowl.'], ['Can a clearer photo make a calorie estimate exact?', 'No. Lighting and framing reduce visual ambiguity, but hidden ingredients, recipes and portion assumptions can still change the result.']],
  },
  {
    topic: 'nutrition', slug: 'ai-calorie-scanner-vs-food-diary', published: '2026-09-22', modified: '2026-09-22',
    title: 'AI Calorie Scanner vs Food Diary: Which Should You Use?',
    description: 'Compare a photo-based AI calorie scanner with manual food logging by speed, portion detail, recipe accuracy and the kind of record each method creates.',
    intro: 'Photo scanning and manual food logging solve different parts of the same problem. One starts quickly from an image; the other can capture known quantities and recipe details that a camera cannot see.',
    takeaway: 'Use photo scanning for a quick visual record, manual entries for known quantities, and a combined approach when hidden ingredients or portions matter.',
    sections: [
      ['Compare what each method starts with', table('Photo scan and manual diary comparison', ['Question', 'AI photo scan', 'Manual food diary'], [
        ['What do you provide?', 'A meal image to analyze', 'Food names, quantities and labels'],
        ['Fastest use case', 'A visible everyday meal', 'A packaged or measured item'],
        ['Main uncertainty', 'Identification and portion size', 'Entry choice and quantity entered'],
        ['Useful record', 'The original meal photo', 'Structured ingredient details'],
      ]) + `<p>Neither method guarantees an exact result. A database entry may not match your recipe, while an image may miss oil, filling or serving depth.</p>`],
      ['Use a photo scan when speed matters', `<p>A photo can be the lowest-friction way to record a meal before eating. It preserves what the plate looked like and gives you a starting estimate without searching for every visible item.</p><p>This is especially useful when the purpose is consistency: capturing lunches, reviewing meal patterns or remembering what you ate. Review the identified foods rather than accepting the first result automatically.</p>`],
      ['Use manual details when you know more than the camera', `<p>For a packaged snack, the nutrition label and amount eaten can be more useful than its appearance. For a homemade meal, ingredient weights, cooking oil and the number of portions provide information a photo cannot recover.</p><p>Manual logging still depends on correct entries. Check whether a database value describes cooked or uncooked food and whether the stated serving matches the amount used.</p>`],
      ['Combine the two methods for mixed meals', `<p>Start with a photo to capture the plate, then keep known ingredients and quantities in a separate food diary. Note the dressing, recipe portion or any misidentified item there. The photograph remains useful context while your manual record preserves details the scan may miss.</p><p>Restaurant meals may require a wider uncertainty range because recipes and added fats are unknown. If the restaurant publishes nutrition information for the exact item, keep that source in your diary alongside the meal date instead of rebuilding the meal from appearance alone.</p><p>You do not need the same method for every meal. Use the amount of detail that supports your purpose without making the routine impossible to maintain.</p>`],
      ['Choose a repeatable NutriLens workflow', `<ol><li>Photograph the complete meal in NutriLens.</li><li>Review the detected foods and estimated nutrition.</li><li>Write known quantities, hidden ingredients and discrepancies in your own food diary.</li><li>Keep the meal date with those notes so you can relate them to the photo later.</li></ol><p>NutriLens offers photo analysis and meal comparison. Saving and revisiting scans is listed as a Premium feature on iOS; check the available options in your version. Keep your diary and scan matched by date so the manual ingredient details remain easy to find.</p><p>Estimates are informational and should not be used for allergy safety or as individualized medical nutrition advice.</p>`],
    ],
    sources: ['portions','energy'],
    faq: [['Is an AI calorie scanner more accurate than manual logging?', 'It depends on the information available. A photo can be convenient, while measured ingredients and labels can provide stronger quantity details. Both methods require review.'], ['Can I use both methods?', 'Yes. Use a photo scan for visual context and a separate food diary for known quantities, hidden ingredients and corrections to your own record.']],
  },
  {
    topic: 'nutrition', slug: 'estimate-portion-size-from-food-photo', published: '2026-09-22', modified: '2026-09-22',
    title: 'How to Estimate Portion Size From a Food Photo',
    description: 'Learn what a meal photo can reveal about portion size, what remains uncertain, and how to add plate, label and recipe context before using an estimate.',
    intro: 'A food photo shows shape and relative space, but it does not automatically provide weight or volume. A useful estimate combines the image with a few facts you already know.',
    takeaway: 'Use the container, visible count and known package or recipe amount as context. Record uncertainty instead of treating visual volume as a measured weight.',
    sections: [
      ['Separate countable items from mixed foods', `<p>Countable items such as slices, eggs or pieces can be described directly when each item is visible. Rice, pasta, soup and mixed dishes are harder because depth and density are not obvious from one angle.</p><p>Start by naming what can be observed without guessing. Then identify which part needs a quantity assumption.</p>`],
      ['Use the plate as context, not a ruler', `<p>A visible plate or bowl helps show how the meal is arranged, but dinnerware is not a standard unit. “Half a bowl” means little unless you know the bowl’s capacity. Perspective can also make the nearest food look larger.</p><p>If you eat from the same container often, measure its capacity once and save that information in your own notes. You can then describe a future serving as an approximate fraction of a known container.</p>`],
      ['Add a second angle for depth', `<p>A top-down photo shows area well but can hide height. A 45-degree or side photo can reveal whether a portion is a thin layer or a deep mound. Keep the full container visible in both images.</p><p>Take both photos before moving or eating the food so they describe the same serving. If you add a sauce or second portion later, record that change separately.</p><p>The second angle reduces one source of ambiguity; it still does not identify exact grams. Use a scale or measured utensil when a measured amount is important.</p>`],
      ['Prefer known quantities when available', table('Evidence to use before visual guessing', ['Available information', 'Note for your food diary'], [
        ['Package says 200 g and half remains', 'Approximately 100 g used'],
        ['Recipe makes four equal portions', 'One quarter of total recipe'],
        ['Two visible slices with label per slice', 'Two labeled servings'],
        ['Unknown restaurant mixed dish', 'Photo estimate with uncertainty note'],
      ]) + `<p>Labels and recipes can still contain rounding or serving assumptions, but they provide a clearer basis than appearance alone.</p>`],
      ['Review a NutriLens estimate against what you know', `<p>Scan the meal, then compare the result with your known context. If you served one quarter of a recipe or used two labeled items, record that quantity in a separate food diary. Note hidden sauces and oils there as well, so an incomplete scan does not become your only record.</p><p>Photos of familiar meals can help you keep portion descriptions consistent. NutriLens supports saved-scan history, which the iOS listing includes in Premium; check current access in your version. Whether a photo is in your camera roll or app history, it remains an estimate rather than an exact measurement.</p>`],
    ],
    sources: ['portions'],
    faq: [['Can a photo tell me the exact grams of food?', 'No. A photo can support a visual estimate, but exact weight requires a measurement or reliable quantity information.'], ['What should I include for scale?', 'Keep the full plate or bowl visible and add known information such as package size, recipe yield or measured utensil volume when available.']],
  },
  {
    topic: 'nutrition', slug: 'photo-calorie-scanner-app-checklist', published: '2026-09-22', modified: '2026-09-22', appPreview: true,
    title: 'Photo Calorie Scanner App: Pre-Save Checklist',
    description: 'Use this photo calorie scanner checklist to review food identity, portion assumptions and hidden ingredients before saving estimated calories and macros.',
    intro: 'A photo calorie scanner can make meal logging faster, but the first result is still a starting point. A short review helps you keep a more useful record without pretending that a camera can measure every ingredient.',
    takeaway: 'Before saving a scan, check whether the foods are identified correctly, whether the portion assumption is plausible and whether oil, dressing, drinks or fillings are missing.',
    sections: [
      ['Know what the camera can and cannot observe', table('What a meal photo can contribute', ['Visible clue', 'Useful for', 'What remains uncertain'], [
        ['Food shape and color', 'Suggesting possible foods', 'Recipe and exact ingredients'],
        ['Relative area on the plate', 'A rough portion starting point', 'Weight, density and depth'],
        ['Visible count', 'Recording slices, pieces or items', 'Size and ingredients inside'],
        ['Container and presentation', 'Adding context to the meal record', 'Container capacity unless known'],
      ]) + `<p>The image may show grilled chicken, rice and vegetables, but it may not reveal how much oil was used, whether the sauce contains sugar or how deep the serving is. Keep those known details in your own notes so you can review the scan with more context.</p>`],
      ['Take a photo that preserves useful context', `<p>Keep the whole plate or bowl inside the frame, use even light and avoid filters that change the food’s color. A roughly 45-degree angle often shows both surface area and height. For a deep bowl or stacked meal, a second angle can clarify depth.</p><p>Include the container rather than cropping tightly around the food. It is context, not a ruler: plates and bowls vary in size. If you use the same container regularly, measure it once and keep that information with your routine.</p><p>For a fuller setup, use the <a href="/guides/how-to-take-food-photos-for-calorie-tracking/">food photo checklist</a> before opening the scanner.</p>`],
      ['Run a three-check review before saving', `<ol><li><strong>Food identity:</strong> does the result describe what is actually on the plate?</li><li><strong>Portion basis:</strong> is the proposed amount consistent with a known package, recipe share or measured quantity?</li><li><strong>Hidden items:</strong> are oil, dressing, sauce, drinks, fillings or toppings missing?</li></ol><p>Write discrepancies in a separate food diary. When you do not know an amount, keep it as an estimate rather than replacing one unknown with a precise-looking guess. The <a href="/guides/estimate-portion-size-from-food-photo/">portion-size guide</a> explains which clues are stronger than visual volume alone.</p>`],
      ['Review a mixed meal step by step', table('Illustrative chicken-and-rice bowl review', ['Part of meal', 'What you know', 'Review action'], [
        ['Chicken', 'Visible pieces; cooking fat unknown', 'Confirm food, note hidden oil uncertainty'],
        ['Rice', 'One quarter of a known four-portion batch', 'Use the recipe share instead of visual guessing'],
        ['Vegetables', 'Visible but partly covered', 'Check identity and avoid false precision'],
        ['Sauce', 'Added after the photo', 'Record it separately in your food diary'],
      ]) + `<p>The goal is not to make every line exact. It is to replace avoidable errors with information you already have. For a homemade batch, the ingredient total and number of portions can be more useful than the appearance of the final serving. See the <a href="/guides/track-calories-homemade-meals/">homemade-meal worksheet</a> for that calculation.</p>`],
      ['Use a label or manual detail when it is stronger evidence', `<p>A packaged item with a readable nutrition label and a known amount may be easier to record manually than to infer from a photograph. The same applies to a recipe you measured while cooking. Photo scanning is most useful when it reduces friction without hiding the uncertainty that still exists.</p><p>You can mix methods: keep the meal photo as a visual record and record the known package quantity or recipe portion in a separate diary. If the calculated value differs from the scan, preserve the source and your calculation there. You can then see where each number came from when reviewing the meal.</p>`],
      ['Build a repeatable NutriLens workflow', `<p>Open NutriLens, photograph the complete meal and review the estimated foods, calories and macros. Keep a dated note of anything missing or uncertain in your own food diary. NutriLens can save scans for later review; the iOS App Store listing includes saving and revisiting meals in Premium. Check the current options in your version before planning to use that history.</p><p>For a first session, choose a familiar meal whose ingredients you know. Compare the analysis with your own notes, then use the same photo setup next time. NutriLens provides informational estimates and should not be used to determine allergy safety or replace individualized advice from a qualified health professional.</p>`],
    ],
    sources: ['portions','energy'],
    faq: [['Can a photo calorie scanner measure an exact portion?', 'No. A photo can support an estimate, but weight, depth, recipe details and hidden ingredients may remain unknown. Use measured or labeled quantities when available.'], ['What should I check first after scanning?', 'Confirm the food names, then review the portion basis and write any missing items such as oil, sauce, dressing, drinks or fillings in your own notes.'], ['How should I record a correction after a scan?', 'Keep the meal date, known quantities and any correction in a separate food diary or note. Keep the original scan estimate distinct from your own calculation so both remain understandable.']],
  },
];
